import {
  PROPERTY_OFFER_SCHEMA_VERSION,
  type CoverageItem,
  type Money,
  type PropertyOffer,
  type SourceRef,
} from "./model";

const money = (amount: number): Money => ({ amount, currency: "CZK" });
const source = (documentId: string, page: number, label?: string): SourceRef => ({
  documentId,
  page,
  ...(label ? { label } : {}),
});

const G1 = source("generali-reference", 1, "souhrn kalkulace a pojistné");
const G2 = source("generali-reference", 2, "rozsah START, limity a spoluúčast");
const G3 = source("generali-reference", 3, "základní asistence");
const U1 = source("uniqa-reference", 1, "rekapitulace a pojistné");
const U2 = source("uniqa-reference", 2, "limity domácnosti");
const U3 = source("uniqa-reference", 3, "rizika domácnosti Mini");
const U4 = source("uniqa-reference", 4, "odpovědnost, asistence a platnost");
const A1 = source("allianz-reference", 1, "varianta EXTRA, pojistné a spoluúčasti");
const A2 = source("allianz-reference", 2, "výčet rizik a dílčí limity");

const generaliCoverages: CoverageItem[] = [
  {
    id: "building-insurance",
    category: "building",
    label: "Pojištění nemovitosti / budovy",
    status: "excluded",
    details: ["Stavba není pojištěna; kalkulace uvádí STAVBA 0 Kč."],
    sourceRefs: [G2],
  },
  {
    id: "basic-perils",
    category: "household",
    label: "Základní živelní rizika",
    status: "included",
    limit: { kind: "fixed", amount: money(430_000), basis: "insurance-event" },
    details: [
      "Požár, kouř, výbuch, přímý úder blesku, vichřice, krupobití, pád předmětů, sesuv, tíha sněhu, zemětřesení a další rizika uvedená v kalkulaci.",
      "Částka 430 000 Kč odpovídá limitu uvedenému pro variantu START.",
    ],
    sourceRefs: [G2],
  },
  {
    id: "water-damage",
    category: "household",
    label: "Vodovodní škody",
    status: "included",
    limit: { kind: "fixed", amount: money(430_000), basis: "insurance-event" },
    details: [],
    sourceRefs: [G2],
  },
  {
    id: "flood-inundation",
    category: "household",
    label: "Povodeň a záplava",
    status: "excluded",
    details: ["Ve zvolené variantě START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "atmospheric-precipitation",
    category: "household",
    label: "Atmosférické srážky",
    status: "excluded",
    details: ["Ve zvolené variantě START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "burglary-robbery",
    category: "household",
    label: "Krádež vloupáním a loupež",
    status: "excluded",
    details: ["Ve zvolené variantě START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "vandalism",
    category: "household",
    label: "Vandalismus a sprejerství",
    status: "excluded",
    details: ["Krytí je v produktu navázáno na vyšší rozsah; v START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "glass",
    category: "household",
    label: "Skla a sanitární zařízení",
    status: "excluded",
    details: ["Ve zvolené variantě START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "electrical-risks",
    category: "household",
    label: "Přepětí, podpětí a zkrat",
    status: "excluded",
    details: ["Ve zvolené variantě START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "lost-water",
    category: "household",
    label: "Náhrada výdajů za ztrátu vody",
    status: "excluded",
    details: ["Ve zvolené variantě START není sjednáno."],
    sourceRefs: [G2],
  },
  {
    id: "civil-liability",
    category: "liability",
    label: "Odpovědnost v běžném občanském životě",
    status: "included",
    limit: { kind: "fixed", amount: money(6_000_000), basis: "unspecified" },
    deductible: { kind: "none", amount: money(0) },
    territory: { code: "EUROPE", label: "Evropa" },
    details: [],
    sourceRefs: [G1],
  },
  {
    id: "property-liability",
    category: "liability",
    label: "Odpovědnost z nemovitostí",
    status: "included",
    limit: { kind: "fixed", amount: money(6_000_000), basis: "unspecified" },
    deductible: { kind: "none", amount: money(0) },
    territory: { code: "CZ", label: "Česká republika" },
    details: [],
    sourceRefs: [G1],
  },
  {
    id: "household-assistance",
    category: "assistance",
    label: "Základní asistence",
    status: "included",
    limit: { kind: "included", note: "Jednotlivé služby mají různé finanční a frekvenční limity." },
    details: [
      "Havarijní stav, zablokování dveří a deratizace: do 10 000 Kč.",
      "Oprava zdroje tepla: do 5 000 Kč, nejvýše 1× ročně.",
      "Právní asistence a ostatní takto označené služby jsou pouze organizační.",
    ],
    sourceRefs: [G3],
  },
];

const uniqaCoverages: CoverageItem[] = [
  {
    id: "building-insurance",
    category: "building",
    label: "Pojištění nemovitosti / budovy",
    status: "excluded",
    details: ["Stavby: nesjednáno."],
    sourceRefs: [U1],
  },
  {
    id: "basic-perils",
    category: "household",
    label: "Základní živelní rizika",
    status: "included",
    limit: { kind: "fixed", amount: money(300_000), basis: "insurance-event" },
    details: ["Požár, úder blesku, výbuch, imploze, pád letadla, rázová vlna, kouř a náraz vozidla."],
    sourceRefs: [U2],
  },
  {
    id: "natural-perils",
    category: "household",
    label: "Další přírodní události",
    status: "included",
    limit: { kind: "fixed", amount: money(300_000), basis: "insurance-event" },
    details: ["Vichřice, krupobití, tíha a pád sněhu, pád stromů a jiných předmětů, sesuv půdy, zemětřesení, lavina a výbuch sopky."],
    sourceRefs: [U3],
  },
  {
    id: "water-damage",
    category: "household",
    label: "Vodovodní škody",
    status: "included",
    limit: { kind: "fixed", amount: money(300_000), basis: "insurance-event" },
    details: ["Únik vody, lom trubky, únik z nádrže a náklady na odstranění závady na vodovodním zařízení."],
    sourceRefs: [U3],
  },
  {
    id: "flood-inundation",
    category: "household",
    label: "Povodeň a záplava",
    status: "excluded",
    details: ["V nabídce Mini je výslovně uvedeno nesjednáno."],
    sourceRefs: [U3],
  },
  {
    id: "atmospheric-precipitation",
    category: "household",
    label: "Zatečení atmosférických srážek",
    status: "included",
    limit: {
      kind: "percentage-of-sum-insured",
      amount: money(30_000),
      percentage: 10,
      minimum: money(20_000),
      basis: "insurance-event",
    },
    details: ["V této kalkulaci odpovídá limit 30 000 Kč."],
    sourceRefs: [U3],
  },
  {
    id: "burglary-robbery",
    category: "household",
    label: "Krádež vloupáním a loupež",
    status: "excluded",
    details: ["Celý blok Odcizení je v nabídce Mini uveden jako nesjednáno."],
    sourceRefs: [U3],
  },
  {
    id: "vandalism",
    category: "household",
    label: "Vandalismus a sprejerství",
    status: "excluded",
    details: ["Je součástí nesjednaného bloku Odcizení."],
    sourceRefs: [U3],
  },
  {
    id: "glass",
    category: "household",
    label: "Skla a sanitární zařízení",
    status: "excluded",
    details: ["Blok Ostatní je v nabídce Mini uveden jako nesjednáno."],
    sourceRefs: [U3],
  },
  {
    id: "electrical-risks",
    category: "household",
    label: "Přepětí, podpětí, nepřímý blesk a zkrat",
    status: "excluded",
    details: ["Blok Ostatní je v nabídce Mini uveden jako nesjednáno."],
    sourceRefs: [U3],
  },
  {
    id: "lost-water",
    category: "household",
    label: "Ztráta vody",
    status: "included",
    limit: {
      kind: "percentage-of-sum-insured",
      amount: money(15_000),
      percentage: 5,
      minimum: money(10_000),
      basis: "insurance-event",
    },
    details: ["V této kalkulaci odpovídá limit 15 000 Kč."],
    sourceRefs: [U3],
  },
  {
    id: "civil-liability",
    category: "liability",
    label: "Odpovědnost v běžném občanském životě",
    status: "included",
    limit: { kind: "fixed", amount: money(5_000_000), basis: "unspecified" },
    deductible: { kind: "fixed", amount: money(1_000) },
    territory: { code: "WORLD", label: "Svět" },
    details: [],
    sourceRefs: [U1, U4],
  },
  {
    id: "property-liability",
    category: "liability",
    label: "Odpovědnost z vlastnictví nebo správy budovy a pozemku",
    status: "included",
    limit: { kind: "fixed", amount: money(5_000_000), basis: "unspecified" },
    deductible: { kind: "fixed", amount: money(1_000) },
    territory: { code: "CZ", label: "Česká republika" },
    details: [],
    sourceRefs: [U1, U4],
  },
  {
    id: "landlord-tenant-liability",
    category: "liability",
    label: "Odpovědnost pronajímatele včetně odpovědnosti nájemce",
    status: "included",
    limit: { kind: "fixed", amount: money(5_000_000), basis: "unspecified" },
    deductible: { kind: "fixed", amount: money(1_000) },
    territory: { code: "CZ", label: "Česká republika" },
    details: [],
    sourceRefs: [U4],
  },
  {
    id: "used-items-liability",
    category: "liability",
    label: "Škoda na cizí věci užívané",
    status: "excluded",
    territory: { code: "WORLD", label: "Svět" },
    details: ["V nabídce je výslovně uvedeno nesjednáno."],
    sourceRefs: [U4],
  },
  {
    id: "livestock-holder-liability",
    category: "liability",
    label: "Odpovědnost držitele hospodářských zvířat",
    status: "excluded",
    territory: { code: "CZ", label: "Česká republika" },
    details: ["V nabídce je výslovně uvedeno nesjednáno."],
    sourceRefs: [U4],
  },
  {
    id: "drone-liability",
    category: "liability",
    label: "Odpovědnost z modelů a dronů",
    status: "excluded",
    territory: { code: "EUROPE", label: "Evropa" },
    details: ["V nabídce je výslovně uvedeno nesjednáno."],
    sourceRefs: [U4],
  },
  {
    id: "household-assistance",
    category: "assistance",
    label: "Technická, právní, rodinná a bytová asistence",
    status: "included",
    limit: { kind: "included" },
    details: ["Součást ceny pojištění; konkrétní finanční limit není v předběžné nabídce uveden."],
    sourceRefs: [U1, U4],
  },
];

const allianzCoverages: CoverageItem[] = [
  {
    id: "building-insurance",
    category: "building",
    label: "Pojištění nemovitosti / budovy",
    status: "excluded",
    details: ["Budova / vedlejší stavby: nesjednáno."],
    sourceRefs: [A1],
  },
  {
    id: "basic-perils",
    category: "household",
    label: "Základní rizika",
    status: "included",
    limit: { kind: "sum-insured", basis: "insurance-event" },
    details: ["Požár a kouř, výbuch, úder blesku, pád letadla a předmětů, náraz vozidla, sesuv a rázová vlna."],
    sourceRefs: [A1, A2],
  },
  {
    id: "natural-perils",
    category: "household",
    label: "Přírodní události",
    status: "included",
    limit: { kind: "sum-insured", basis: "insurance-event" },
    details: ["Vichřice, krupobití, povodeň, záplava, atmosférické srážky, tíha a tlak sněhu."],
    sourceRefs: [A1, A2],
  },
  {
    id: "earthquake",
    category: "household",
    label: "Zemětřesení",
    status: "included",
    details: ["Ve zvolené variantě EXTRA je riziko zahrnuto."],
    sourceRefs: [A1, A2],
  },
  {
    id: "water-damage",
    category: "household",
    label: "Vodovodní škody",
    status: "included",
    limit: { kind: "sum-insured", basis: "insurance-event" },
    details: ["Voda z vodovodního nebo sprinklerového zařízení, vystoupnutí vody z odpadu, mráz a voda z akvária."],
    sourceRefs: [A1, A2],
  },
  {
    id: "flood-inundation",
    category: "household",
    label: "Povodeň a záplava",
    status: "included",
    limit: { kind: "sum-insured", basis: "insurance-event" },
    deductible: {
      kind: "fixed",
      amount: money(5_000),
      note: "Spoluúčast domácnosti; kalkulace uvádí 15 000 Kč pro budovu a 5 000 Kč pro domácnost.",
    },
    details: ["Součást přírodních událostí ve zvolené variantě EXTRA."],
    sourceRefs: [A1, A2],
  },
  {
    id: "atmospheric-precipitation",
    category: "household",
    label: "Atmosférické srážky",
    status: "included",
    limit: { kind: "fixed", amount: money(50_000), basis: "insurance-event" },
    details: [],
    sourceRefs: [A2],
  },
  {
    id: "glass",
    category: "household",
    label: "Rozbití skla",
    status: "included",
    limit: { kind: "fixed", amount: money(30_000), basis: "insurance-event" },
    details: [],
    sourceRefs: [A1, A2],
  },
  {
    id: "burglary-robbery",
    category: "household",
    label: "Krádež a loupež",
    status: "excluded",
    details: ["Riziko Krádež obsahuje až varianta MAX; ve zvolené variantě EXTRA není zahrnuto."],
    sourceRefs: [A1, A2],
  },
  {
    id: "vandalism",
    category: "household",
    label: "Vandalismus",
    status: "excluded",
    details: ["Riziko Vandalismus obsahuje až varianta MAX; ve zvolené variantě EXTRA není zahrnuto."],
    sourceRefs: [A1, A2],
  },
  {
    id: "electrical-risks",
    category: "household",
    label: "Přepětí, podpětí a zkrat",
    status: "excluded",
    details: ["Riziko Elektro obsahuje až varianta MAX; ve zvolené variantě EXTRA není zahrnuto."],
    sourceRefs: [A1, A2],
  },
  {
    id: "lost-water",
    category: "household",
    label: "Náhrada výdajů za ztrátu vody",
    status: "unknown",
    details: ["Kalkulace uvádí vodovodní škody, ale samostatnou náhradu ceny uniklé vody výslovně neuvádí."],
    sourceRefs: [A2],
  },
  {
    id: "civil-liability",
    category: "liability",
    label: "Odpovědnost v běžném občanském životě",
    status: "included",
    deductible: { kind: "none", amount: money(0) },
    territory: { code: "NOT_STATED", label: "V kalkulaci neuvedeno" },
    details: ["Běžná činnost, vedení domácnosti, rekreační sport, chov zvířat, malá plavidla a svépomocné stavební práce."],
    sourceRefs: [A1, A2],
  },
  {
    id: "tenant-liability",
    category: "liability",
    label: "Odpovědnost za pronajatou budovu nebo byt",
    status: "included",
    deductible: { kind: "none", amount: money(0) },
    territory: { code: "NOT_STATED", label: "V kalkulaci neuvedeno" },
    details: [],
    sourceRefs: [A2],
  },
  {
    id: "property-liability",
    category: "liability",
    label: "Samostatná odpovědnost z vlastnictví nemovitosti",
    status: "unknown",
    territory: { code: "NOT_STATED", label: "V kalkulaci neuvedeno" },
    details: ["Výčet zahrnuje vedení domácnosti a pronajatou budovu nebo byt, samostatný rozsah odpovědnosti vlastníka ale kalkulace neodděluje."],
    sourceRefs: [A2],
  },
  {
    id: "household-assistance",
    category: "assistance",
    label: "Asistence a právní poradenství",
    status: "included",
    limit: { kind: "fixed", amount: money(10_000), basis: "service-call", frequencyPerYear: 4 },
    details: ["Odvrácení stavu nouze včetně deratizace a dezinsekce a porucha domácích spotřebičů."],
    sourceRefs: [A1, A2],
  },
];

export const REFERENCE_PROPERTY_OFFER: PropertyOffer = {
  schemaVersion: PROPERTY_OFFER_SCHEMA_VERSION,
  id: "property-offer-reference-2026-07-20",
  title: "Srovnání pojištění nemovitosti, domácnosti a odpovědnosti",
  issueDate: "2026-07-20",
  generatedAt: "2026-07-20T14:10:00+02:00",
  client: {
    name: "Referenční klient",
    sourceRefs: [],
  },
  advisor: {
    name: "Bc. Miloš Weber",
    company: "LIMMIT s.r.o.",
    email: "milos.weber@limmit.cz",
    phone: "+420 777 557 253",
    sourceRefs: [],
  },
  insuredLocation: {
    addressLine: "Anonymizovaná adresa",
    postalCode: "000 00",
    city: "Most",
    objectType: "apartment",
    occupancy: "permanent",
    floorAreaM2: 55,
    floor: "Přízemí",
    sourceRefs: [G1, U1, A1],
  },
  sourceDocuments: [
    {
      id: "generali-reference",
      fileName: "Nabidka-Generali.pdf",
      insurer: "Generali Česká pojišťovna a.s.",
      documentType: "calculation",
      pageCount: 3,
    },
    {
      id: "uniqa-reference",
      fileName: "Nabidka-UNIQA.pdf",
      insurer: "UNIQA pojišťovna, a.s.",
      documentType: "preliminary-offer",
      pageCount: 4,
    },
    {
      id: "allianz-reference",
      fileName: "Nabidka-Allianz.pdf",
      insurer: "Allianz pojišťovna, a.s.",
      documentType: "calculation",
      pageCount: 2,
      createdAt: "2026-07-20T14:03:00+02:00",
    },
  ],
  variants: [
    {
      id: "generali-start",
      insurer: {
        id: "generali",
        name: "Generali Česká pojišťovna a.s.",
        shortName: "Generali",
      },
      product: "Můj majetek",
      packageName: "START",
      annualPremium: money(1_068),
      premiumBreakdown: [
        { id: "household", label: "Domácnost", annualPremium: money(456), sourceRefs: [G1] },
        { id: "civil-liability", label: "Odpovědnost v běžném životě", annualPremium: money(490), sourceRefs: [G1] },
        { id: "property-liability", label: "Odpovědnost z nemovitostí", annualPremium: money(122), sourceRefs: [G1] },
        { id: "assistance", label: "Základní asistence", annualPremium: money(0), sourceRefs: [G1, G3] },
      ],
      validity: {
        issuedOn: "2026-07-20",
        validUntil: null,
        kind: "not-stated",
        note: "Kalkulace neuvádí datum konce platnosti a je označena jako nezávazná a orientační.",
        sourceRefs: [G1, G3],
      },
      building: {
        status: "excluded",
        sumInsured: money(0),
        deductible: { kind: "unknown" },
        guaranteedSumInsured: null,
        limits: [],
        sourceRefs: [G2],
      },
      household: {
        status: "included",
        sumInsured: money(300_000),
        deductible: { kind: "fixed", amount: money(1_000) },
        guaranteedSumInsured: null,
        limits: [
          { id: "non-residential-spaces", label: "Věci v nebytových prostorech", limit: { kind: "fixed", amount: money(30_000) }, sourceRefs: [G2] },
          { id: "special-value-items", label: "Věci zvláštní hodnoty", limit: { kind: "fixed", amount: money(30_000) }, sourceRefs: [G2] },
          { id: "building-components", label: "Stavební součásti", limit: { kind: "fixed", amount: money(100_000) }, sourceRefs: [G2] },
        ],
        sourceRefs: [G1, G2],
      },
      liability: {
        status: "included",
        limit: { kind: "fixed", amount: money(6_000_000), basis: "unspecified" },
        deductible: { kind: "none", amount: money(0) },
        scopes: generaliCoverages.filter((coverage) => coverage.category === "liability"),
        sourceRefs: [G1],
      },
      assistance: {
        status: "included",
        annualPremium: money(0),
        coverages: generaliCoverages.filter((coverage) => coverage.category === "assistance"),
        sourceRefs: [G1, G3],
      },
      coverages: generaliCoverages,
      highlights: [
        "Nejnižší roční pojistné ze tří porovnávaných variant.",
        "Nejvyšší limit odpovědnosti v tomto srovnání: 6 mil. Kč.",
        "Odpovědnost je bez spoluúčasti; běžný občanský život platí v Evropě a odpovědnost z nemovitostí v ČR.",
      ],
      gaps: [
        "Nekryje povodeň a záplavu, krádež, vandalismus, skla, atmosférické srážky ani elektrická rizika.",
        "Konec platnosti kalkulace není ve zdroji uveden.",
      ],
      sourceRefs: [G1, G2, G3],
    },
    {
      id: "uniqa-mini-plus",
      insurer: {
        id: "uniqa",
        name: "UNIQA pojišťovna, a.s.",
        shortName: "UNIQA",
      },
      product: "Domov & bezpečí",
      packageName: "Domácnost Mini + odpovědnost Plus",
      annualPremium: money(1_371),
      premiumBreakdown: [
        { id: "household", label: "Domácnost Mini", annualPremium: money(793), sourceRefs: [U1, U3] },
        { id: "liability", label: "Odpovědnost Plus", annualPremium: money(578), sourceRefs: [U1, U4] },
        { id: "assistance", label: "Základní asistence", annualPremium: money(0), sourceRefs: [U1, U4] },
      ],
      validity: {
        issuedOn: "2026-07-20",
        validUntil: "2026-08-20",
        kind: "period-from-issue",
        note: "Předběžná nabídka platí jeden měsíc od data vystavení.",
        sourceRefs: [U1, U4],
      },
      building: {
        status: "excluded",
        sumInsured: money(0),
        deductible: { kind: "unknown" },
        guaranteedSumInsured: null,
        limits: [],
        sourceRefs: [U1],
      },
      household: {
        status: "included",
        sumInsured: money(300_000),
        deductible: { kind: "fixed", amount: money(1_000) },
        guaranteedSumInsured: false,
        limits: [
          { id: "building-components", label: "Stavební součásti domácnosti", limit: { kind: "percentage-of-sum-insured", amount: money(90_000), percentage: 30 }, sourceRefs: [U2] },
          { id: "non-residential-spaces", label: "Věci v nebytových prostorech", limit: { kind: "percentage-of-sum-insured", amount: money(90_000), percentage: 30 }, sourceRefs: [U2] },
          { id: "common-building-spaces", label: "Věci ve společných prostorech domu", limit: { kind: "fixed", amount: money(100_000) }, sourceRefs: [U2] },
          { id: "fenced-property", label: "Věci na oploceném pozemku", limit: { kind: "fixed", amount: money(30_000) }, sourceRefs: [U2] },
          { id: "vehicle-luggage-compartment", label: "Věci v zavazadlovém prostoru auta (Evropa)", limit: { kind: "fixed", amount: money(50_000) }, sourceRefs: [U2] },
          { id: "temporary-stay-accommodation", label: "Věci v místě dočasného pobytu nebo ubytování (Evropa)", limit: { kind: "percentage-of-sum-insured", amount: money(30_000), percentage: 10 }, sourceRefs: [U2] },
          { id: "valuables", label: "Cennosti", limit: { kind: "percentage-of-sum-insured", amount: money(60_000), percentage: 20 }, sourceRefs: [U2] },
          { id: "money-securities", label: "Peníze a ceniny", limit: { kind: "percentage-of-sum-insured", amount: money(30_000), percentage: 10, minimum: money(20_000) }, sourceRefs: [U2] },
          { id: "special-value-items", label: "Věci zvláštní hodnoty", limit: { kind: "percentage-of-sum-insured", amount: money(60_000), percentage: 20 }, sourceRefs: [U2] },
          { id: "animals", label: "Domácí a drobné zvířectvo", limit: { kind: "percentage-of-sum-insured", amount: money(60_000), percentage: 20 }, sourceRefs: [U2] },
          { id: "business-items", label: "Věci k výkonu výdělečné činnosti", limit: { kind: "percentage-of-sum-insured", amount: money(30_000), percentage: 10, minimum: money(20_000) }, sourceRefs: [U2] },
          { id: "offsite-garage", label: "Věci v garáži mimo místo pojištění v téže obci", limit: { kind: "fixed", amount: money(100_000) }, sourceRefs: [U2] },
          { id: "debris-removal", label: "Odklízecí a bourací náklady", limit: { kind: "percentage-of-sum-insured", amount: money(30_000), percentage: 10 }, sourceRefs: [U2] },
          { id: "lock-replacement", label: "Výměna zámků", limit: { kind: "fixed", amount: money(5_000) }, sourceRefs: [U2] },
          { id: "temporary-accommodation", label: "Náhradní ubytování", limit: { kind: "fixed", amount: money(150_000) }, sourceRefs: [U2] },
        ],
        sourceRefs: [U1, U2, U3],
      },
      liability: {
        status: "included",
        limit: { kind: "fixed", amount: money(5_000_000), basis: "unspecified" },
        deductible: { kind: "fixed", amount: money(1_000) },
        scopes: uniqaCoverages.filter((coverage) => coverage.category === "liability"),
        sourceRefs: [U1, U4],
      },
      assistance: {
        status: "included",
        annualPremium: money(0),
        coverages: uniqaCoverages.filter((coverage) => coverage.category === "assistance"),
        sourceRefs: [U1, U4],
      },
      coverages: uniqaCoverages,
      highlights: [
        "Zatečení atmosférických srážek do 30 000 Kč a ztráta vody do 15 000 Kč jsou zahrnuty.",
        "Odpovědnost v běžném občanském životě má světový územní rozsah.",
        "Technická, právní, rodinná a bytová asistence je v ceně.",
      ],
      gaps: [
        "Nekryje povodeň a záplavu, krádež, vandalismus, skla ani elektrická rizika.",
        "Odpovědnost za cizí užívané věci, držitele hospodářských zvířat a za modely či drony není sjednána.",
        "Pojistná částka domácnosti není v předběžné nabídce garantována.",
      ],
      sourceRefs: [U1, U2, U3, U4],
    },
    {
      id: "allianz-extra",
      insurer: {
        id: "allianz",
        name: "Allianz pojišťovna, a.s.",
        shortName: "Allianz",
      },
      product: "MůjDomov",
      packageName: "EXTRA",
      annualPremium: money(1_631),
      premiumBreakdown: [
        { id: "combined", label: "Domácnost EXTRA a odpovědnost", annualPremium: money(1_631), sourceRefs: [A1] },
      ],
      validity: {
        issuedOn: "2026-07-20",
        validUntil: "2026-08-20",
        kind: "until-date",
        note: "Kalkulace výslovně uvádí platnost do 20. 8. 2026.",
        sourceRefs: [A1],
      },
      building: {
        status: "excluded",
        sumInsured: money(0),
        deductible: { kind: "unknown" },
        guaranteedSumInsured: null,
        limits: [],
        sourceRefs: [A1],
      },
      household: {
        status: "included",
        sumInsured: money(300_000),
        deductible: {
          kind: "fixed",
          amount: money(1_000),
          note: "Obecná spoluúčast; pro povodeň a záplavu domácnosti platí 5 000 Kč.",
        },
        guaranteedSumInsured: null,
        limits: [
          { id: "glass", label: "Rozbití skla", limit: { kind: "fixed", amount: money(30_000), basis: "insurance-event" }, sourceRefs: [A2] },
          { id: "atmospheric-precipitation", label: "Atmosférické srážky", limit: { kind: "fixed", amount: money(50_000), basis: "insurance-event" }, sourceRefs: [A2] },
          { id: "temporary-accommodation", label: "Náhradní ubytování", limit: { kind: "fixed", amount: money(25_000), basis: "insurance-event", maximumDurationMonths: 6 }, sourceRefs: [A2] },
          { id: "storage-after-loss", label: "Uskladnění po škodě", limit: { kind: "fixed", amount: money(25_000), basis: "insurance-event", maximumDurationMonths: 6 }, sourceRefs: [A2] },
          { id: "money-securities", label: "Peníze, ceniny a vklady", limit: { kind: "fixed", amount: money(15_000), basis: "insurance-event" }, sourceRefs: [A2] },
          { id: "valuables", label: "Cennosti", limit: { kind: "percentage-of-sum-insured", amount: money(30_000), percentage: 10, basis: "insurance-event", note: "10 % pojistné částky" }, sourceRefs: [A2] },
          { id: "building-components", label: "Stavební součásti", limit: { kind: "fixed", amount: money(50_000), basis: "insurance-event" }, sourceRefs: [A2] },
          { id: "secondary-spaces", label: "Vedlejší prostory", limit: { kind: "fixed", amount: money(30_000), basis: "insurance-event" }, sourceRefs: [A2] },
        ],
        sourceRefs: [A1, A2],
      },
      liability: {
        status: "included",
        limit: { kind: "fixed", amount: money(5_000_000), basis: "insurance-year" },
        deductible: { kind: "none", amount: money(0) },
        scopes: allianzCoverages.filter((coverage) => coverage.category === "liability"),
        sourceRefs: [A1, A2],
      },
      assistance: {
        status: "included",
        annualPremium: null,
        coverages: allianzCoverages.filter((coverage) => coverage.category === "assistance"),
        sourceRefs: [A1, A2],
      },
      coverages: allianzCoverages,
      highlights: [
        "Jediná z porovnávaných variant zahrnuje současně povodeň a záplavu, vodovodní škody, atmosférické srážky a skla.",
        "Asistence má uvedený limit 10 000 Kč na zásah, nejvýše 4× ročně.",
        "Odpovědnost je bez spoluúčasti.",
      ],
      gaps: [
        "Ve variantě EXTRA nejsou zahrnuty krádež, vandalismus ani rizika přepětí, podpětí a zkratu; ta obsahuje až MAX.",
        "Náhrada ceny uniklé vody není v kalkulaci výslovně potvrzena.",
        "Územní rozsah odpovědnosti není v kalkulaci uveden a je třeba jej před sjednáním ověřit.",
        "Pro povodeň a záplavu domácnosti platí spoluúčast 5 000 Kč, nikoli obecná spoluúčast 1 000 Kč.",
      ],
      sourceRefs: [A1, A2],
    },
  ],
  recommendation: {
    variantId: "allianz-extra",
    label: "Doporučená volba v tomto srovnání",
    summary:
      "Allianz EXTRA je nejširší z porovnávaných variant v klíčových rizicích domácnosti. Jako jediná z této trojice zahrnuje současně povodeň a záplavu, vodovodní škody, atmosférické srážky i skla. Nejde o tvrzení, že je obecně nebo absolutně nejlepší.",
    rationale: [
      "Povodeň a záplava jsou zahrnuté; Generali START ani UNIQA Mini je sjednané nemají.",
      "Zahrnuje vodovodní škody, atmosférické srážky a rozbití skla; u skel je uveden limit 30 000 Kč.",
      "Za 1 631 Kč ročně je Allianz EXTRA nejdražší z porovnávaných variant; UNIQA Mini + Plus stojí 1 371 Kč a Generali START 1 068 Kč ročně.",
    ],
    caveats: [
      "Žádná z porovnávaných nabídek nepojišťuje samotnou nemovitost nebo budovu; sjednáno je pojištění domácnosti a odpovědnosti.",
      "EXTRA nekryje krádež, vandalismus ani přepětí, podpětí a zkrat. Pro tato rizika by bylo nutné ověřit a přepočítat variantu MAX.",
      "Spoluúčast domácnosti při povodni a záplavě je 5 000 Kč.",
      "Limit odpovědnosti 5 mil. Kč je nižší než 6 mil. Kč u Generali a územní rozsah Allianz není v kalkulaci uveden.",
      "Samostatná náhrada ceny uniklé vody není v kalkulaci Allianz výslovně uvedena.",
    ],
    sourceRefs: [G1, G2, U1, U3, U4, A1, A2],
  },
};
