begin;
update attendance_private.settings set gateway_hash=encode(extensions.digest('auth-test-only','sha256'),'hex');
insert into attendance_private.accounts(username,password_hash)
select username,extensions.crypt('Test-password-123456',extensions.gen_salt('bf',4)) from attendance_private.people
on conflict(username) do update set password_hash=excluded.password_hash,must_change_password=false;
do $test$
declare r jsonb; v_token text:=repeat('v',43); n_token text:=repeat('n',43); n2_token text:=repeat('z',43); mid uuid; i int;
begin
 r:=public.account_gateway('auth-test-only',v_token,'login','{"username":"VIKTOR","password":"wrong","ip":"test-admin"}');
 assert (r->>'status')::int=401,'Wrong password rejected';
 r:=public.account_gateway('auth-test-only',v_token,'login','{"username":"VIKTOR","password":"Test-password-123456","ip":"test-admin","user_agent":"Test browser"}');
 assert r->>'username'='VIKTOR','Admin login';
 r:=public.account_gateway('auth-test-only',n_token,'login','{"username":"NIKOLA","password":"Test-password-123456","ip":"test-employee"}');
 assert r->>'username'='NIKOLA','Employee login';
 mid:=(r->>'session_id')::uuid;
 r:=public.account_gateway('auth-test-only',n2_token,'login','{"username":"NIKOLA","password":"Test-password-123456","ip":"test-second"}');
 r:=public.account_gateway('auth-test-only',n_token,'list','{}');
 assert not (r->>'can_manage_team')::boolean and jsonb_array_length(r->'people')=1,'Employee sees own account';
 assert not exists(select 1 from jsonb_array_elements(r->'sessions') x where x->>'username'<>'NIKOLA'),'No other devices exposed';
 assert position('token_hash' in r::text)=0 and position('password_hash' in r::text)=0,'Secrets not listed';
 r:=public.account_gateway('auth-test-only',n_token,'password','{"username":"VIKTOR","password":"new-test-pass-123"}');
 assert (r->>'status')::int=403,'No escalation';
 r:=public.account_gateway('auth-test-only',n_token,'revoke_all','{"username":"VIKTOR"}');
 assert (r->>'status')::int=403,'No cross-user revoke';
 r:=public.account_gateway('auth-test-only',v_token,'revoke',jsonb_build_object('username','NIKOLA','session_id',mid));
 assert (r->>'ok')::boolean,'Admin revokes one device';
 r:=public.account_gateway('auth-test-only',n_token,'check','{}');assert (r->>'status')::int=401,'Revoked token rejected';
 r:=public.account_gateway('auth-test-only',n2_token,'check','{}');assert r->>'username'='NIKOLA','Other device still active';
 r:=public.account_gateway('auth-test-only',v_token,'password','{"username":"NIKOLA","password":"Updated-test-password-123"}');
 assert (r->>'ok')::boolean,'Admin password reset';
 r:=public.account_gateway('auth-test-only',n2_token,'check','{}');assert (r->>'status')::int=401,'Password reset revokes all';
 r:=public.account_gateway('auth-test-only',n_token,'login','{"username":"NIKOLA","password":"Test-password-123456","ip":"test-old"}');
 assert (r->>'status')::int=401,'Old password invalid';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'login','{"username":"NIKOLA","password":"Updated-test-password-123","ip":"test-new"}');
 assert r->>'username'='NIKOLA','New password works';
 assert (r->>'must_change_password')::boolean,'Admin reset requires personal password';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'check','{}');
 assert (r->>'status')::int=403 and r->>'username' is null,'Temporary password cannot access protected operations';
 r:=public.account_task_action('auth-test-only',repeat('x',43),'create',gen_random_uuid(),'{"title":"Must not create"}');
 assert (r->>'status')::int=403,'Task API cannot bypass password change';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'list','{}');
 assert (r->>'status')::int=403,'Device management also blocked';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'session','{}');
 assert r->>'username'='NIKOLA' and (r->>'must_change_password')::boolean,'Restricted identity available';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'initial_password','{"username":"VIKTOR","password":"Personal-password-456"}');
 assert (r->>'status')::int=403,'Initial change only self';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'initial_password','{"password":"Updated-test-password-123"}');
 assert (r->>'status')::int=400,'Temporary password cannot be reused';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'initial_password','{"password":"short"}');
 assert (r->>'status')::int=400,'Short personal password rejected';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'initial_password','{"password":"Personal-password-456"}');
 assert (r->>'ok')::boolean,'Personal password saved';
 r:=public.account_gateway('auth-test-only',repeat('x',43),'check','{}');
 assert (r->>'status')::int=401,'Initial change revokes temporary session';
 r:=public.account_gateway('auth-test-only',repeat('y',43),'login','{"username":"NIKOLA","password":"Updated-test-password-123","ip":"test-old-temp"}');
 assert (r->>'status')::int=401,'Temporary password no longer works';
 r:=public.account_gateway('auth-test-only',repeat('y',43),'login','{"username":"NIKOLA","password":"Personal-password-456","ip":"test-personal"}');
 assert not (r->>'must_change_password')::boolean,'Personal login no longer needs change';
 r:=public.account_gateway('auth-test-only',repeat('y',43),'check','{}');
 assert r->>'username'='NIKOLA','Personal password unlocks normal access';
 r:=public.account_gateway('auth-test-only',repeat('y',43),'initial_password','{"password":"Unwanted-password-789"}');
 assert (r->>'status')::int=400,'Initial endpoint cannot change established password';
 r:=public.account_gateway('auth-test-only',repeat('y',43),'password','{"username":"NIKOLA","old_password":"wrong","password":"Another-test-password-123"}');
 assert (r->>'status')::int=400,'Own password needs current password';
 r:=public.account_gateway('auth-test-only',repeat('y',43),'logout','{}');
 r:=public.account_gateway('auth-test-only',repeat('y',43),'check','{}');assert (r->>'status')::int=401,'Logout invalidates server token';
 for i in 1..11 loop r:=public.account_gateway('auth-test-only',repeat('q',43),'login','{"username":"UNKNOWN","password":"bad","ip":"test-throttle"}');end loop;
 assert (r->>'status')::int=429,'Login throttling persists';
 r:=public.account_gateway('auth-test-only','old.signed.cookie','check','{}');assert (r->>'status')::int=401,'Legacy cookie rejected';
 assert not has_table_privilege('anon','attendance_private.accounts','select'),'Password table private';
 assert not has_table_privilege('anon','attendance_private.login_sessions','select'),'Sessions private';
end $test$;
select 'Account authentication and revocation tests passed' as result;
do $bridge$
declare r jsonb; v_id uuid:=gen_random_uuid();
begin
 r:=public.account_task_action('auth-test-only',repeat('v',43),'create',v_id,'{"title":"Rollback auth test","assignees":["Viktor"],"priority":"Low"}');
 assert (r->>'ok')::boolean,'Authenticated task mutation';
 assert (select created_by='Viktor' from public.tasks where id=v_id),'Actor from session';
 r:=public.account_task_action('auth-test-only',repeat('n',43),'comment',v_id,'{"body":"Should never be stored"}');
 assert (r->>'status')::int=401,'Revoked task session rejected';
 assert not has_function_privilege('anon','public.task_workspace(text,text,uuid,jsonb)','execute'),'Direct task mutation closed';
end $bridge$;
rollback;
