begin;
update attendance_private.settings set gateway_hash=encode(extensions.digest('half-day-test','sha256'),'hex');
do $test$
declare v_id uuid:=gen_random_uuid(); n_id uuid:=gen_random_uuid(); b boolean; snap jsonb; remaining integer; person text;
begin
 foreach person in array array['KARINA','VENDULA','MILOS','NIKOLA','KATERINA','LUKAS','MILAN','VIKTOR'] loop
  v_id:=gen_random_uuid();
  remaining:=attendance_private.vacation_remaining(person,2097);
  perform attendance_private.gateway('half-day-test',person,'request',jsonb_build_object('id',v_id,'kind','VACATION','vacation_part','AM','date_from','2097-02-04','date_to','2097-02-04','year',2097));
  assert (select status='PENDING' and time_from='08:30' and vacation_part='AM' from attendance_private.requests where id=v_id),'Everyone can request a half day';
  assert attendance_private.vacation_remaining(person,2097)=remaining-(select daily_hours*30 from attendance_private.people where username=person),'Exactly half daily hours reserved';
  perform attendance_private.gateway('half-day-test',person,'cancel_request',jsonb_build_object('id',v_id,'year',2097));
  assert attendance_private.vacation_remaining(person,2097)=remaining,'Cancellation restores balance';
 end loop;
 v_id:=gen_random_uuid();
 perform attendance_private.gateway('half-day-test','KARINA','request',jsonb_build_object('id',v_id,'kind','VACATION','vacation_part','AM','date_from','2097-02-04','date_to','2097-02-04','year',2097));
 assert attendance_private.absence_minutes('KARINA','2097-02-04','2097-02-04 20:00+01')=420,'Pending leave does not excuse absence';
 perform attendance_private.gateway('half-day-test','VIKTOR','review_request',jsonb_build_object('id',v_id,'decision','APPROVED','year',2097));
 assert (select time_to='12:00' from attendance_private.requests where id=v_id),'7 hour shift midpoint';
 assert attendance_private.absence_minutes('KARINA','2097-02-04','2097-02-04 20:00+01')=210,'Only approved half excluded from absence';
 assert (select sum(extract(epoch from upper(r)-lower(r)))/60=210 from attendance_private.absence_periods('KARINA','2097-02-04','2097-02-04 20:00+01') r),'Excuse periods respect half day';
 perform attendance_private.gateway('half-day-test','KARINA','home_plan','{"year":2097,"week":"2097-02-04","days":["2097-02-04"]}');
 assert exists(select 1 from attendance_private.home_days where username='KARINA' and day='2097-02-04'),'Home office for remaining half';
 b:=false;
 begin perform attendance_private.gateway('half-day-test','KARINA','request',jsonb_build_object('id',gen_random_uuid(),'kind','PERSONAL','date_from','2097-02-04','date_to','2097-02-04','time_from','10:00','time_to','11:00'));exception when others then b:=true;end;
 assert b,'Personal overlap rejected';
 perform attendance_private.gateway('half-day-test','VIKTOR','request',jsonb_build_object('id',gen_random_uuid(),'target_username','KARINA','kind','VACATION','vacation_part','PM','date_from','2097-02-04','date_to','2097-02-04','year',2097));
 assert attendance_private.absence_minutes('KARINA','2097-02-04','2097-02-04 20:00+01')=0,'Two approved halves cover full day';
 assert attendance_private.vacation_remaining('KARINA',2097)=7980,'Two halves debit one day';
 snap:=attendance_private.gateway('half-day-test','KARINA','snapshot','{"year":2097}');
 assert (snap->'balances'->0->>'approved')::numeric=1,'Day totals correct';
 assert exists(select 1 from jsonb_array_elements(snap->'requests') r where (r->>'days')::numeric=0.5),'Requests report half days';
 perform attendance_private.gateway('half-day-test','VIKTOR','request',jsonb_build_object('id',n_id,'target_username','NIKOLA','kind','VACATION','vacation_part','PM','date_from','2097-02-04','date_to','2097-02-04','year',2097));
 assert (select status='APPROVED' and time_from='13:00' and time_to='17:30' from attendance_private.requests where id=n_id),'Owner entry uses 9 hour shift';
 assert attendance_private.vacation_remaining('NIKOLA',2097)=10530,'9 hour half = 270 minutes';
 b:=false;
 begin perform attendance_private.gateway('half-day-test','NIKOLA','request',jsonb_build_object('id',gen_random_uuid(),'kind','VACATION','vacation_part','PM','date_from','2097-02-04','date_to','2097-02-04'));exception when others then b:=true;end;
 assert b,'Duplicate half rejected';
 b:=false;
 begin perform attendance_private.gateway('half-day-test','NIKOLA','request',jsonb_build_object('id',gen_random_uuid(),'kind','VACATION','date_from','2097-02-04','date_to','2097-02-04'));exception when others then b:=true;end;
 assert b,'Full day overlapping half rejected';
 b:=false;
 begin perform attendance_private.gateway('half-day-test','NIKOLA','request',jsonb_build_object('id',gen_random_uuid(),'kind','VACATION','vacation_part','AM','date_from','2097-02-05','date_to','2097-02-06'));exception when others then b:=true;end;
 assert b,'Multiday half rejected';
 b:=false;
 begin perform attendance_private.gateway('half-day-test','NIKOLA','request',jsonb_build_object('id',gen_random_uuid(),'kind','VACATION','vacation_part','AM','date_from','2097-01-01','date_to','2097-01-01'));exception when others then b:=true;end;
 assert b,'Holiday rejected';
 perform attendance_private.gateway('half-day-test','VIKTOR','set_vacation_balance','{"target_username":"NIKOLA","year":2097,"remaining_days":0.5}');
 perform attendance_private.gateway('half-day-test','NIKOLA','request',jsonb_build_object('id',gen_random_uuid(),'kind','VACATION','vacation_part','AM','date_from','2097-02-05','date_to','2097-02-05','year',2097));
 assert attendance_private.vacation_remaining('NIKOLA',2097)=0,'Last half day accepted';
 b:=false;
 begin perform attendance_private.gateway('half-day-test','NIKOLA','request',jsonb_build_object('id',gen_random_uuid(),'kind','VACATION','vacation_part','PM','date_from','2097-02-05','date_to','2097-02-05'));exception when others then b:=true;end;
 assert b,'Insufficient half day rejected';
end $test$;
select 'Half-day vacation tests passed' as result;
rollback;
